#!/usr/bin/env python3
import os
import argparse
import speedtest

def get_formatted_speed(s):
    unit = ""
    if s > 1024**3:
        s = s / 1024**3
        unit = "G"
    elif s > 1024**2:
        s = s / 1024**2
        unit = "M"
    elif s > 1024:
        s = s / 1024
        unit = "K"
    return f"{s:.0f}{unit}"



parser = argparse.ArgumentParser()
parser.add_argument('--upload', action="store_true")
parser.add_argument('--bytes', action="store_true")
args= parser.parse_args()

try:
    s = speedtest.Speedtest()
except:
    printf("NOSPD")
    exit(0)

if args.upload:
    s.upload(pre_allocate=False)
    print(get_formatted_speed(s.results.upload))
else:
    s.download()
    print(get_formatted_speed(s.results.download))
